// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v3.21.12
// source: config.proto

package agentpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ManageAgentOps_ExecuteCommands_FullMethodName = "/ManageAgentOps/ExecuteCommands"
	ManageAgentOps_CreateFiles_FullMethodName     = "/ManageAgentOps/CreateFiles"
	ManageAgentOps_ViewFile_FullMethodName        = "/ManageAgentOps/ViewFile"
)

// ManageAgentOpsClient is the client API for ManageAgentOps service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ManageAgentOpsClient interface {
	ExecuteCommands(ctx context.Context, in *ExecuteCommandsRequest, opts ...grpc.CallOption) (*ExecuteCommandsResponse, error)
	CreateFiles(ctx context.Context, in *CreateFileRequest, opts ...grpc.CallOption) (*CreateFileResponse, error)
	ViewFile(ctx context.Context, in *ViewFileRequest, opts ...grpc.CallOption) (*ViewFileResponse, error)
}

type manageAgentOpsClient struct {
	cc grpc.ClientConnInterface
}

func NewManageAgentOpsClient(cc grpc.ClientConnInterface) ManageAgentOpsClient {
	return &manageAgentOpsClient{cc}
}

func (c *manageAgentOpsClient) ExecuteCommands(ctx context.Context, in *ExecuteCommandsRequest, opts ...grpc.CallOption) (*ExecuteCommandsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ExecuteCommandsResponse)
	err := c.cc.Invoke(ctx, ManageAgentOps_ExecuteCommands_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *manageAgentOpsClient) CreateFiles(ctx context.Context, in *CreateFileRequest, opts ...grpc.CallOption) (*CreateFileResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateFileResponse)
	err := c.cc.Invoke(ctx, ManageAgentOps_CreateFiles_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *manageAgentOpsClient) ViewFile(ctx context.Context, in *ViewFileRequest, opts ...grpc.CallOption) (*ViewFileResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ViewFileResponse)
	err := c.cc.Invoke(ctx, ManageAgentOps_ViewFile_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ManageAgentOpsServer is the server API for ManageAgentOps service.
// All implementations must embed UnimplementedManageAgentOpsServer
// for forward compatibility.
type ManageAgentOpsServer interface {
	ExecuteCommands(context.Context, *ExecuteCommandsRequest) (*ExecuteCommandsResponse, error)
	CreateFiles(context.Context, *CreateFileRequest) (*CreateFileResponse, error)
	ViewFile(context.Context, *ViewFileRequest) (*ViewFileResponse, error)
	mustEmbedUnimplementedManageAgentOpsServer()
}

// UnimplementedManageAgentOpsServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedManageAgentOpsServer struct{}

func (UnimplementedManageAgentOpsServer) ExecuteCommands(context.Context, *ExecuteCommandsRequest) (*ExecuteCommandsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ExecuteCommands not implemented")
}
func (UnimplementedManageAgentOpsServer) CreateFiles(context.Context, *CreateFileRequest) (*CreateFileResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateFiles not implemented")
}
func (UnimplementedManageAgentOpsServer) ViewFile(context.Context, *ViewFileRequest) (*ViewFileResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ViewFile not implemented")
}
func (UnimplementedManageAgentOpsServer) mustEmbedUnimplementedManageAgentOpsServer() {}
func (UnimplementedManageAgentOpsServer) testEmbeddedByValue()                        {}

// UnsafeManageAgentOpsServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ManageAgentOpsServer will
// result in compilation errors.
type UnsafeManageAgentOpsServer interface {
	mustEmbedUnimplementedManageAgentOpsServer()
}

func RegisterManageAgentOpsServer(s grpc.ServiceRegistrar, srv ManageAgentOpsServer) {
	// If the following call panics, it indicates UnimplementedManageAgentOpsServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ManageAgentOps_ServiceDesc, srv)
}

func _ManageAgentOps_ExecuteCommands_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExecuteCommandsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ManageAgentOpsServer).ExecuteCommands(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ManageAgentOps_ExecuteCommands_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ManageAgentOpsServer).ExecuteCommands(ctx, req.(*ExecuteCommandsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ManageAgentOps_CreateFiles_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateFileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ManageAgentOpsServer).CreateFiles(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ManageAgentOps_CreateFiles_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ManageAgentOpsServer).CreateFiles(ctx, req.(*CreateFileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ManageAgentOps_ViewFile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ViewFileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ManageAgentOpsServer).ViewFile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ManageAgentOps_ViewFile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ManageAgentOpsServer).ViewFile(ctx, req.(*ViewFileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ManageAgentOps_ServiceDesc is the grpc.ServiceDesc for ManageAgentOps service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ManageAgentOps_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "ManageAgentOps",
	HandlerType: (*ManageAgentOpsServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ExecuteCommands",
			Handler:    _ManageAgentOps_ExecuteCommands_Handler,
		},
		{
			MethodName: "CreateFiles",
			Handler:    _ManageAgentOps_CreateFiles_Handler,
		},
		{
			MethodName: "ViewFile",
			Handler:    _ManageAgentOps_ViewFile_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "config.proto",
}
