// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v3.21.12
// source: config.proto

package agentpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ExecuteCommandsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cmds          []string               `protobuf:"bytes,1,rep,name=cmds,proto3" json:"cmds,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecuteCommandsRequest) Reset() {
	*x = ExecuteCommandsRequest{}
	mi := &file_config_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteCommandsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteCommandsRequest) ProtoMessage() {}

func (x *ExecuteCommandsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_config_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteCommandsRequest.ProtoReflect.Descriptor instead.
func (*ExecuteCommandsRequest) Descriptor() ([]byte, []int) {
	return file_config_proto_rawDescGZIP(), []int{0}
}

func (x *ExecuteCommandsRequest) GetCmds() []string {
	if x != nil {
		return x.Cmds
	}
	return nil
}

type ExecuteCommandsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecuteCommandsResponse) Reset() {
	*x = ExecuteCommandsResponse{}
	mi := &file_config_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteCommandsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteCommandsResponse) ProtoMessage() {}

func (x *ExecuteCommandsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_config_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteCommandsResponse.ProtoReflect.Descriptor instead.
func (*ExecuteCommandsResponse) Descriptor() ([]byte, []int) {
	return file_config_proto_rawDescGZIP(), []int{1}
}

func (x *ExecuteCommandsResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type CreateFileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Files         []string               `protobuf:"bytes,1,rep,name=files,proto3" json:"files,omitempty"`
	Contents      []string               `protobuf:"bytes,2,rep,name=contents,proto3" json:"contents,omitempty"`
	AppName       string                 `protobuf:"bytes,3,opt,name=app_name,json=appName,proto3" json:"app_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateFileRequest) Reset() {
	*x = CreateFileRequest{}
	mi := &file_config_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateFileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateFileRequest) ProtoMessage() {}

func (x *CreateFileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_config_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateFileRequest.ProtoReflect.Descriptor instead.
func (*CreateFileRequest) Descriptor() ([]byte, []int) {
	return file_config_proto_rawDescGZIP(), []int{2}
}

func (x *CreateFileRequest) GetFiles() []string {
	if x != nil {
		return x.Files
	}
	return nil
}

func (x *CreateFileRequest) GetContents() []string {
	if x != nil {
		return x.Contents
	}
	return nil
}

func (x *CreateFileRequest) GetAppName() string {
	if x != nil {
		return x.AppName
	}
	return ""
}

type CreateFileResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateFileResponse) Reset() {
	*x = CreateFileResponse{}
	mi := &file_config_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateFileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateFileResponse) ProtoMessage() {}

func (x *CreateFileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_config_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateFileResponse.ProtoReflect.Descriptor instead.
func (*CreateFileResponse) Descriptor() ([]byte, []int) {
	return file_config_proto_rawDescGZIP(), []int{3}
}

func (x *CreateFileResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type ViewFileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ViewFileRequest) Reset() {
	*x = ViewFileRequest{}
	mi := &file_config_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ViewFileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ViewFileRequest) ProtoMessage() {}

func (x *ViewFileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_config_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ViewFileRequest.ProtoReflect.Descriptor instead.
func (*ViewFileRequest) Descriptor() ([]byte, []int) {
	return file_config_proto_rawDescGZIP(), []int{4}
}

func (x *ViewFileRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

type ViewFileResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ViewFileResponse) Reset() {
	*x = ViewFileResponse{}
	mi := &file_config_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ViewFileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ViewFileResponse) ProtoMessage() {}

func (x *ViewFileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_config_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ViewFileResponse.ProtoReflect.Descriptor instead.
func (*ViewFileResponse) Descriptor() ([]byte, []int) {
	return file_config_proto_rawDescGZIP(), []int{5}
}

func (x *ViewFileResponse) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

var File_config_proto protoreflect.FileDescriptor

const file_config_proto_rawDesc = "" +
	"\n" +
	"\fconfig.proto\",\n" +
	"\x16ExecuteCommandsRequest\x12\x12\n" +
	"\x04cmds\x18\x01 \x03(\tR\x04cmds\"1\n" +
	"\x17ExecuteCommandsResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\"`\n" +
	"\x11CreateFileRequest\x12\x14\n" +
	"\x05files\x18\x01 \x03(\tR\x05files\x12\x1a\n" +
	"\bcontents\x18\x02 \x03(\tR\bcontents\x12\x19\n" +
	"\bapp_name\x18\x03 \x01(\tR\aappName\",\n" +
	"\x12CreateFileResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\"%\n" +
	"\x0fViewFileRequest\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\"&\n" +
	"\x10ViewFileResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code2\xbf\x01\n" +
	"\x0eManageAgentOps\x12D\n" +
	"\x0fExecuteCommands\x12\x17.ExecuteCommandsRequest\x1a\x18.ExecuteCommandsResponse\x126\n" +
	"\vCreateFiles\x12\x12.CreateFileRequest\x1a\x13.CreateFileResponse\x12/\n" +
	"\bViewFile\x12\x10.ViewFileRequest\x1a\x11.ViewFileResponseB\x1dZ\x1borderservice/common;agentpbb\x06proto3"

var (
	file_config_proto_rawDescOnce sync.Once
	file_config_proto_rawDescData []byte
)

func file_config_proto_rawDescGZIP() []byte {
	file_config_proto_rawDescOnce.Do(func() {
		file_config_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_config_proto_rawDesc), len(file_config_proto_rawDesc)))
	})
	return file_config_proto_rawDescData
}

var file_config_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_config_proto_goTypes = []any{
	(*ExecuteCommandsRequest)(nil),  // 0: ExecuteCommandsRequest
	(*ExecuteCommandsResponse)(nil), // 1: ExecuteCommandsResponse
	(*CreateFileRequest)(nil),       // 2: CreateFileRequest
	(*CreateFileResponse)(nil),      // 3: CreateFileResponse
	(*ViewFileRequest)(nil),         // 4: ViewFileRequest
	(*ViewFileResponse)(nil),        // 5: ViewFileResponse
}
var file_config_proto_depIdxs = []int32{
	0, // 0: ManageAgentOps.ExecuteCommands:input_type -> ExecuteCommandsRequest
	2, // 1: ManageAgentOps.CreateFiles:input_type -> CreateFileRequest
	4, // 2: ManageAgentOps.ViewFile:input_type -> ViewFileRequest
	1, // 3: ManageAgentOps.ExecuteCommands:output_type -> ExecuteCommandsResponse
	3, // 4: ManageAgentOps.CreateFiles:output_type -> CreateFileResponse
	5, // 5: ManageAgentOps.ViewFile:output_type -> ViewFileResponse
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_config_proto_init() }
func file_config_proto_init() {
	if File_config_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_config_proto_rawDesc), len(file_config_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_config_proto_goTypes,
		DependencyIndexes: file_config_proto_depIdxs,
		MessageInfos:      file_config_proto_msgTypes,
	}.Build()
	File_config_proto = out.File
	file_config_proto_goTypes = nil
	file_config_proto_depIdxs = nil
}
